# Generated by Django 4.2.6 on 2023-10-22 16:35

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneticAlgorithmInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_size', models.PositiveIntegerField()),
                ('num_generations', models.PositiveIntegerField()),
                ('num_selected', models.PositiveIntegerField()),
                ('num_children', models.PositiveIntegerField()),
                ('crossover_probability', models.FloatField()),
                ('mutation_probability', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MusicalRepresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_signature', models.CharField(max_length=5)),
                ('scale_signature', models.CharField(max_length=10)),
                ('tempo', models.PositiveIntegerField()),
                ('has_back_track', models.BooleanField()),
                ('uses_arp_or_scale', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedMelody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mel', cloudinary.models.CloudinaryField(max_length=255, verbose_name='melody')),
                ('average_ratings', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('generation', models.PositiveIntegerField(default=1)),
                ('duration', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_rating', models.ManyToManyField(to='genetic.evaluation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='mel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genetic.generatedmelody'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField(default=0.0)),
                ('img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('ga_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genetic.geneticalgorithminfo')),
                ('melodies', models.ManyToManyField(to='genetic.generatedmelody')),
                ('musical_representation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genetic.musicalrepresentation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('user', 'mel')},
        ),
    ]
