# Generated by Django 4.2.6 on 2023-10-23 17:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genetic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='img',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dgb26cwpx/image/upload/v1698017763/album_cover_default_pdxmu4.png', max_length=255, verbose_name='image'),
        ),
    ]
