# Generated by Django 4.2.6 on 2023-10-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genetic', '0002_alter_album_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmelody',
            name='user_rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
