# Generated by Django 4.2.6 on 2023-10-31 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genetic', '0003_generatedmelody_user_rating_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedmelody',
            name='user_rating_count',
        ),
    ]
