# Generated by Django 4.2.6 on 2023-11-10 04:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=50)),
                ('tempo', models.CharField(max_length=10)),
                ('meter', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(max_length=10)),
                ('mel', cloudinary.models.CloudinaryField(max_length=255, verbose_name='melody')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedMusicAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dgb26cwpx/image/upload/v1698017763/album_cover_default_pdxmu4.png', max_length=255, verbose_name='image')),
                ('epoch', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('generated_music', models.ManyToManyField(to='rnn.generatedmusic')),
            ],
        ),
    ]
