# Generated by Django 4.2.6 on 2023-10-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rnn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedmusicalbum',
            name='epoch',
            field=models.IntegerField(default=0),
        ),
    ]
